"""Prepare the checksum-pinned Windows native SDK without installing anything.

Requires 64-bit CPython 3.12 and the Visual Studio C++ developer environment.
Only C DLL boundaries are used; lib.exe creates MSVC import libraries from PE
exports. MinGW static libraries and headers for the MinGW CRT are never linked.
"""

import argparse
from concurrent.futures import ThreadPoolExecutor
import hashlib
import json
from pathlib import Path
import shutil
import subprocess
import sys
import tarfile
import zipfile

ROOT = Path(__file__).resolve().parents[2]
LOCK_PATH = Path(__file__).with_name("native-lock.json")
CACHE = ROOT / "target/windows-x86_64"
CARGO_CONFIG_MARKER = "# Generated by packaging/windows/prepare.py for this Windows checkout."


def configure_cargo(paths):
    """Configure dependency build scripts before Cargo starts compiling them."""
    config = ROOT / ".cargo/config.toml"
    if config.with_suffix("").exists():
        raise RuntimeError("Existing .cargo/config takes precedence; merge or rename it before preparing Windows Cargo configuration.")
    if config.exists() and not config.read_text(encoding="utf-8").startswith(CARGO_CONFIG_MARKER):
        raise RuntimeError("Refusing to overwrite your .cargo/config.toml. Merge the Windows SDK environment and runner settings manually, or move that file before preparing again.")
    sdk = Path(paths["sdk"])
    environment = dict(
        FFMPEG_DIR=str(sdk),
        PKG_CONFIG=paths["pkg_config"],
        PKG_CONFIG_PATH=str(sdk / "lib/pkgconfig"),
        PKG_CONFIG_LIBDIR=str(sdk / "lib/pkgconfig"),
        LIBCLANG_PATH=paths["libclang"],
        BINDGEN_EXTRA_CLANG_ARGS=f'-I"{sdk / "include"}"',
    )
    runner = [paths["python"], str(ROOT / "packaging/windows/run.py")]
    # JSON strings and arrays also work as TOML values, including escaped paths.
    encode = lambda value: json.dumps(value, ensure_ascii=False)
    text = CARGO_CONFIG_MARKER + "\n# Local paths only; do not commit. Re-run preparation after moving the checkout.\n\n[env]\n"
    text += "".join(f"{name} = {encode(value)}\n" for name, value in environment.items())
    text += "\n[target.x86_64-pc-windows-msvc]\nrunner = " + encode(runner) + "\n"
    config.parent.mkdir(exist_ok=True)
    config.write_text(text, encoding="utf-8")
    print(f"Cargo development environment ready: {config}", flush=True)


def sha256(path):
    with path.open("rb") as stream:
        return hashlib.file_digest(stream, "sha256").hexdigest()


def download(item, offline=False):
    path = CACHE / "downloads" / item["filename"]
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and sha256(path) == item["sha256"]:
        return path
    if offline:
        raise RuntimeError(f"Missing or corrupt cached dependency: {path}")
    print(f"Downloading {item['filename']}", flush=True)
    partial = path.with_suffix(path.suffix + ".part")
    subprocess.run([
        "curl.exe", "--fail", "--location", "--silent", "--show-error",
        "--retry", "3", "--connect-timeout", "30", "--max-time", "600",
        "--output", str(partial), item["url"],
    ], check=True)
    if sha256(partial) != item["sha256"]:
        raise RuntimeError(f"SHA256 mismatch: {item['filename']}")
    partial.replace(path)
    return path


def safe_path(root, name):
    path = (root / name).resolve()
    if not path.is_relative_to(root.resolve()):
        raise RuntimeError(f"Unsafe archive path: {name}")
    return path


def extract_zip(archive, destination):
    with zipfile.ZipFile(archive) as source:
        for member in source.infolist():
            path = safe_path(destination, member.filename)
            if member.is_dir():
                path.mkdir(parents=True, exist_ok=True)
            else:
                path.parent.mkdir(parents=True, exist_ok=True)
                with source.open(member) as stream, path.open("wb") as output:
                    shutil.copyfileobj(stream, output)


def load_tools(lock, offline=False):
    if sys.version_info[:2] != (3, 12) or sys.maxsize <= 2**32:
        raise RuntimeError("Use 64-bit Python 3.12 (the native tool wheels are pinned).")
    destination = CACHE / "tools/python"
    for item in lock["tools"]:
        archive = download(item, offline)
        marker = destination / (item["name"] + ".sha256")
        if not marker.exists() or marker.read_text() != item["sha256"]:
            extract_zip(archive, destination)
            marker.write_text(item["sha256"])
    sys.path.insert(0, str(destination))
    return destination


def extract_msys(item):
    import zstandard

    destination = CACHE / "native/msys"
    metadata = CACHE / "native/package-info" / item["name"]
    metadata.mkdir(parents=True, exist_ok=True)
    marker = metadata / "sha256"
    if marker.exists() and marker.read_text() == item["sha256"]:
        return
    archive = CACHE / "downloads" / item["filename"]
    with archive.open("rb") as compressed:
        with zstandard.ZstdDecompressor().stream_reader(compressed) as stream:
            with tarfile.open(fileobj=stream, mode="r|") as source:
                for member in source:
                    if not member.isfile():
                        continue
                    if member.name.startswith("ucrt64/"):
                        path = safe_path(destination, member.name)
                    elif member.name in (".PKGINFO", ".BUILDINFO"):
                        path = metadata / member.name.removeprefix(".")
                    else:
                        continue
                    path.parent.mkdir(parents=True, exist_ok=True)
                    with source.extractfile(member) as content, path.open("wb") as output:
                        shutil.copyfileobj(content, output)
    marker.write_text(item["sha256"])


def import_library(dll, output, lib_tool):
    import pefile

    pe = pefile.PE(str(dll))
    if pe.FILE_HEADER.Machine != 0x8664:
        raise RuntimeError(f"Expected an x64 DLL: {dll}")
    lines = [f'LIBRARY "{dll.name}"', "EXPORTS"]
    for symbol in pe.DIRECTORY_ENTRY_EXPORT.symbols:
        if not symbol.name:
            continue
        name = symbol.name.decode("ascii")
        section = pe.get_section_by_rva(symbol.address)
        data = section is not None and not section.Characteristics & 0x20000000
        lines.append(name + (" DATA" if data and not symbol.forwarder else ""))
    pe.close()
    definition = output.with_suffix(".def")
    definition.write_text("\n".join(lines) + "\n", encoding="ascii")
    subprocess.run([lib_tool, "/nologo", "/machine:x64", f"/def:{definition}",
                    f"/out:{output}"], check=True, stdout=subprocess.DEVNULL)


def prepare(offline=False):
    lock = json.loads(LOCK_PATH.read_text())
    tools = load_tools(lock, offline)
    items = [lock["ffmpeg"], *lock["packages"]]
    with ThreadPoolExecutor(max_workers=4) as pool:
        list(pool.map(lambda item: download(item, offline), items))
    for item in lock["packages"]:
        extract_msys(item)
    ffmpeg_dir = CACHE / "native/ffmpeg"
    marker = ffmpeg_dir / "sha256"
    if not marker.exists() or marker.read_text() != lock["ffmpeg"]["sha256"]:
        extract_zip(CACHE / "downloads" / lock["ffmpeg"]["filename"], ffmpeg_dir)
        marker.write_text(lock["ffmpeg"]["sha256"])
    ffmpeg = next(path.parent for path in ffmpeg_dir.glob("*/include"))
    msys = CACHE / "native/msys/ucrt64"
    sdk = CACHE / "sdk"
    include = sdk / "include"
    library = sdk / "lib"
    library.mkdir(parents=True, exist_ok=True)
    shutil.copytree(ffmpeg / "include", include, dirs_exist_ok=True)
    for name in ("libplacebo", "vulkan", "vk_video"):
        shutil.copytree(msys / "include" / name, include / name, dirs_exist_ok=True)
    lib_tool = shutil.which("lib.exe")
    if not lib_tool:
        raise RuntimeError("lib.exe not found; run from the x64 Visual Studio developer shell.")
    for name in ("avcodec", "avformat", "avutil", "avfilter", "swresample", "swscale"):
        dll = next((ffmpeg / "bin").glob(name + "-*.dll"))
        import_library(dll, library / (name + ".lib"), lib_tool)
    import_library(msys / "bin/libplacebo-360.dll", library / "placebo.lib", lib_tool)
    pkgconfig = library / "pkgconfig"
    pkgconfig.mkdir(exist_ok=True)
    # Paths are quoted because the SDK may be in a checkout containing spaces.
    for name, version, libs in (("libplacebo", "7.360.1", "-lplacebo"),
                                ("libavutil", "61.3.100", "-lavutil")):
        if name == "libavutil":
            import re
            major_text = (include / "libavutil/version.h").read_text()
            version_parts = [re.search(r"#define\s+LIBAVUTIL_VERSION_" + part + r"\s+(\d+)",
                                       major_text).group(1) for part in ("MAJOR", "MINOR", "MICRO")]
            version = ".".join(version_parts)
        (pkgconfig / (name + ".pc")).write_text(
            f"prefix={sdk.as_posix()}\nlibdir=${{prefix}}/lib\nincludedir=${{prefix}}/include\n"
            f"Name: {name}\nDescription: Tiny Player Windows native SDK\nVersion: {version}\n"
            f'Libs: -L"${{libdir}}" {libs}\nCflags: -I"${{includedir}}"\n')
    paths = dict(python=sys.executable, sdk=str(sdk), ffmpeg=str(ffmpeg), msys=str(msys),
                 libclang=str(next(tools.rglob("libclang.dll")).parent), pkg_config=str(msys / "bin/pkgconf.exe"),
                 tools=str(tools))
    (CACHE / "paths.json").write_text(json.dumps(paths, indent=2) + "\n")
    configure_cargo(paths)
    print(f"Native SDK ready: {sdk}", flush=True)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--offline", action="store_true")
    prepare(parser.parse_args().offline)
