//! Development settings cache rows in their original display order.
use super::*;

impl PlaybackSettingsDialogState {
    pub(super) fn cache_items(&self, dialog: Entity<Self>, cx: &App) -> [SettingItem; 24] {
        use SettingsCategory::*;
        let cache_dir = SettingItem::new(
            Disk,
            "存储与清理",
            "缓存目录",
            "实际缓存存储目录，由播放器管理，不可修改。",
            "cache_dir path",
            self.render_cache_directories(cx),
        );
        [
            SettingItem::new(
                General,
                "缓存模式",
                "普通缓存",
                "自动模式根据媒体来源决定是否启用缓存。",
                "mode auto",
                mode_selector(
                    dialog.clone(),
                    self.controller.view_model().config.mode,
                    self.dropdown.clone(),
                ),
            ),
            SettingItem::new(
                General,
                "缓存模式",
                "回看缓存",
                "保留已读取的数据，以便向后跳转和重复播放。",
                "seekable_cache seek",
                seekable_selector(
                    dialog.clone(),
                    self.controller.view_model().config.seekable_cache,
                    self.dropdown.clone(),
                ),
            ),
            SettingItem::new(
                General,
                "缓冲与暂停",
                "缓冲不足时暂停",
                "等待缓存补充后再继续播放，减少断续播放。",
                "cache_pause cache-pause",
                toggle(
                    &dialog,
                    cx,
                    ToggleSetting::CachePause,
                    "缓冲不足时暂停",
                    self.controller.view_model().config.cache_pause,
                ),
            ),
            SettingItem::new(
                General,
                "缓冲与暂停",
                "启动时等待缓存",
                "启用缓冲暂停时，先积累缓存再开始播放。",
                "cache_pause_initial",
                toggle(
                    &dialog,
                    cx,
                    ToggleSetting::CachePauseInitial,
                    "启动时等待缓存",
                    self.controller.view_model().config.cache_pause_initial,
                ),
            ),
            SettingItem::new(
                General,
                "缓冲与暂停",
                "恢复播放阈值",
                "缓冲暂停后，至少缓存多少秒再恢复播放。",
                "cache_pause_wait",
                NumberControl::new(
                    ("cache-pause-wait", "恢复播放阈值"),
                    self.cache_pause_wait_secs.clone(),
                    "秒",
                    NumberRange::seconds(),
                    self.controller.view_model().config.cache_pause_wait,
                ),
            ),
            SettingItem::new(
                General,
                "缓冲与暂停",
                "等待预读完成",
                "开始播放前，等待解复用缓存达到预读目标。",
                "demuxer_cache_wait demux",
                toggle(
                    &dialog,
                    cx,
                    ToggleSetting::DemuxerCacheWait,
                    "等待预读完成",
                    self.controller.view_model().config.demuxer_cache_wait,
                ),
            ),
            SettingItem::new(
                Memory,
                "共享预算",
                "总缓存上限",
                "按 HTTP、前向、回看顺序分配。0 表示各自独立限额。",
                "total_cache_max_bytes",
                NumberControl::new(
                    ("total-cache", "总缓存上限"),
                    self.total_cache_mib.clone(),
                    "MiB",
                    NumberRange::integer(0, 999_999_999_999),
                    bytes_to_mib(self.controller.view_model().config.total_cache_max_bytes) as f64,
                ),
            ),
            SettingItem::new(
                Memory,
                "HTTP 缓存",
                "网络内存缓存",
                "为已下载的媒体数据保留的内存上限。",
                "http_cache_max_bytes",
                NumberControl::new(
                    ("http-cache", "网络内存缓存"),
                    self.http_cache_mib.clone(),
                    "MiB",
                    NumberRange::integer(0, 999_999_999_999),
                    bytes_to_mib(self.controller.view_model().config.http_cache_max_bytes) as f64,
                ),
            ),
            SettingItem::new(
                Memory,
                "HTTP 缓存",
                "分页块大小",
                "网络缓存每个数据块的大小。",
                "http_cache_chunk_bytes",
                NumberControl::new(
                    ("http-cache-chunk", "分页块大小"),
                    self.http_cache_chunk_mib.clone(),
                    "MiB",
                    NumberRange::integer(0, 16),
                    bytes_to_mib(self.controller.view_model().config.http_cache_chunk_bytes) as f64,
                ),
            ),
            SettingItem::new(
                Memory,
                "HTTP 缓存",
                "Range 请求大小",
                "单次 HTTP 范围请求读取的数据量。",
                "http_cache_range_request_bytes",
                NumberControl::new(
                    ("range-request", "Range 请求大小"),
                    self.range_request_mib.clone(),
                    "MiB",
                    NumberRange::integer(0, 128),
                    bytes_to_mib(
                        self.controller
                            .view_model()
                            .config
                            .http_cache_range_request_bytes,
                    ) as f64,
                ),
            ),
            SettingItem::new(
                Memory,
                "解复用缓存",
                "前向缓存上限",
                "分配前向内存预算；启用磁盘缓存后按此比例扩展媒体窗口。0 表示用尽可用预算。",
                "demuxer_max_bytes demux",
                NumberControl::new(
                    ("demuxer-forward", "前向缓存上限"),
                    self.demuxer_forward_mib.clone(),
                    "MiB",
                    NumberRange::integer(0, 999_999_999_999),
                    bytes_to_mib(self.controller.view_model().config.demuxer_max_bytes) as f64,
                ),
            ),
            SettingItem::new(
                Memory,
                "解复用缓存",
                "回看缓存上限",
                "分配回看内存预算，并确定磁盘回看空间比例。0 表示关闭。",
                "demuxer_max_back_bytes demux",
                NumberControl::new(
                    ("demuxer-back", "回看缓存上限"),
                    self.demuxer_back_mib.clone(),
                    "MiB",
                    NumberRange::integer(0, 999_999_999_999),
                    bytes_to_mib(self.controller.view_model().config.demuxer_max_back_bytes) as f64,
                ),
            ),
            SettingItem::new(
                Memory,
                "解复用缓存",
                "保留区间数量",
                "最多保留多少个可供跳转的缓存区间。",
                "demuxer_max_ranges demux range",
                NumberControl::new(
                    ("max-ranges", "保留区间数量"),
                    self.max_ranges.clone(),
                    "个",
                    NumberRange::integer(1, 64),
                    self.controller.view_model().config.demuxer_max_ranges as f64,
                ),
            ),
            SettingItem::new(
                Memory,
                "解复用缓存",
                "共享空闲前向预算",
                "允许回看缓存使用尚未占用的前向预算。",
                "demuxer_donate_buffer demux",
                toggle(
                    &dialog,
                    cx,
                    ToggleSetting::DonateBuffer,
                    "共享空闲前向预算",
                    self.controller.view_model().config.demuxer_donate_buffer,
                ),
            ),
            SettingItem::new(
                Disk,
                "存储与清理",
                "启用磁盘缓存",
                "将较远的数据存入磁盘，扩大预读和回看范围。",
                "disk_cache",
                toggle(
                    &dialog,
                    cx,
                    ToggleSetting::DiskCache,
                    "启用磁盘缓存",
                    self.controller.view_model().config.disk_cache,
                ),
            ),
            SettingItem::new(
                Disk,
                "存储与清理",
                "磁盘缓存上限",
                "限制磁盘缓存使用的空间。",
                "disk_cache_max_bytes",
                disk_cache_capacity_control(
                    self.disk_cache_gib.clone(),
                    self.controller.view_model().config.disk_cache_max_bytes,
                ),
            ),
            cache_dir,
            SettingItem::new(
                Disk,
                "存储与清理",
                "缓存文件清理",
                "选择何时移除磁盘上的缓存文件。",
                "unlink_files",
                unlink_selector(
                    dialog.clone(),
                    self.controller.view_model().config.unlink_files,
                    self.dropdown.clone(),
                ),
            ),
            SettingItem::new(
                Readahead,
                "预读时长",
                "网络缓存目标",
                "网络播放时希望提前缓存的时长，仍受容量上限约束。",
                "cache_secs",
                NumberControl::new(
                    ("cache-secs", "网络缓存目标"),
                    self.cache_secs.clone(),
                    "秒",
                    NumberRange::seconds(),
                    self.controller.view_model().config.cache_secs,
                ),
            ),
            SettingItem::new(
                Readahead,
                "预读时长",
                "解复用预读",
                "提前读取并准备待解码数据的时长。",
                "demuxer_readahead_secs demux",
                NumberControl::new(
                    ("readahead-secs", "解复用预读"),
                    self.readahead_secs.clone(),
                    "秒",
                    NumberRange::seconds(),
                    self.controller.view_model().config.demuxer_readahead_secs,
                ),
            ),
            SettingItem::new(
                Readahead,
                "预读时长",
                "数据包预读上限",
                "限制数据包提前读取的时长。0 表示不限。",
                "demuxer_packet_max_readahead_secs packet",
                NumberControl::new(
                    ("packet-readahead-secs", "数据包预读上限"),
                    self.packet_readahead_secs.clone(),
                    "秒",
                    NumberRange::seconds(),
                    self.controller
                        .view_model()
                        .config
                        .demuxer_packet_max_readahead_secs,
                ),
            ),
            SettingItem::new(
                Readahead,
                "动态调整",
                "自适应预读",
                "根据下载速度调整网络分段请求大小。",
                "adaptive_readahead",
                toggle(
                    &dialog,
                    cx,
                    ToggleSetting::AdaptiveReadahead,
                    "自适应预读",
                    self.controller.view_model().config.adaptive_readahead,
                ),
            ),
            SettingItem::new(
                Readahead,
                "动态调整",
                "自动补充阈值",
                "自动决定缓存消耗多少后开始补充，避免频繁读停。",
                "automatic_hysteresis 自动滞回",
                toggle(
                    &dialog,
                    cx,
                    ToggleSetting::AutomaticHysteresis,
                    "自动补充阈值",
                    self.controller.view_model().config.automatic_hysteresis,
                ),
            ),
            SettingItem::new(
                Readahead,
                "动态调整",
                "补充间隔",
                "缓存消耗多少秒后开始补充。启用自动阈值时，0 表示自动。",
                "demuxer_hysteresis_secs 滞回带",
                NumberControl::new(
                    ("hysteresis-secs", "补充间隔"),
                    self.hysteresis_secs.clone(),
                    "秒",
                    NumberRange::seconds(),
                    self.controller.view_model().config.demuxer_hysteresis_secs,
                ),
            ),
        ]
    }
}
